#!/usr/bin/env bash

SCREENSHOT_DIR="$HOME/Pictures/screenshots"
mkdir -p "$SCREENSHOT_DIR"

FILE="$SCREENSHOT_DIR/screenshot-$(date '+%Y-%m-%d_%H-%M-%S').png"

if [ "$1" = "full" ]; then
    grim "$FILE"
else
    grim -g "$(slurp)" "$FILE" || exit 0
fi

wl-copy < "$FILE"

notify-send \
    -t 1800 \
    "Screenshot saved" \
    "$(basename "$FILE")"