[global]
    background = "#10141C"
    foreground = "#F1F3ED"
    frame_color = "#B9D86B"

[urgency_low]
    background = "#10141C"
    foreground = "#8992A1"
    frame_color = "#7CC7D9"

[urgency_normal]
    background = "#181E28"
    foreground = "#F1F3ED"
    frame_color = "#B9D86B"

[urgency_critical]
    background = "#3A2028"
    foreground = "#FFE8EA"
    frame_color = "#EF7180"
