background #090A0C
foreground #E7E4DC
selection_background #2A2520
selection_foreground #F1EDE4
cursor #D6A85F
cursor_text_color #090A0C
color0 #111318
color1 #C46D6D
color2 #8FA6A0
color3 #D6A85F
color4 #78889A
color5 #9A879A
color6 #7FA09A
color7 #BFC0BA
color8 #4C5057
color9 #D77C7C
color10 #A7BCB5
color11 #E2BA70
color12 #91A0B0
color13 #B39AB3
color14 #94B6AF
color15 #E7E4DC