-- =========================================================
-- RICE — DYNAMIC HYPRLAND COLORS
-- Generated by Matugen
-- =========================================================

return {
    accent = "{{colors.primary.dark.hex}}",
    secondary = "{{colors.secondary.dark.hex}}",
    danger = "{{colors.error.dark.hex}}",
    inactive = "{{colors.outline.dark.hex}}",
    signal = "{{colors.primary_container.dark.hex}}",
}
