"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false

format = """
[▌](fg:{{colors.primary.dark.hex}}) $directory\
$git_branch\
$git_status\
$character
"""

[directory]
style = "fg:{{colors.on_background.dark.hex}}"
format = "[$path]($style) "
truncation_length = 3
truncate_to_repo = false
read_only = " 󰌾"

[git_branch]
symbol = "󰊢 "
style = "fg:{{colors.secondary.dark.hex}}"
format = "[$symbol$branch]($style) "

[git_status]
style = "fg:{{colors.primary.dark.hex}}"
format = "([$all_status$ahead_behind]($style)) "

[character]
success_symbol = "[›](fg:{{colors.primary.dark.hex}})"
error_symbol = "[›](fg:{{colors.error.dark.hex}})"
vimcmd_symbol = "[‹](fg:{{colors.secondary.dark.hex}})"
